favicon: null
name: paau
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1068088999018073
  brandStrength: 0.4822934
  lightness: 0.7136465136427432
  brandColors:
    - '#060604'
    - '#615A4A'
    - '#FFFFFD'
    - '#8F8E89'
    - '#D3604E'
  rhythmicContrast: 0.7329864525236189
typography_spectrum: 0.3214547771494836
layout_spectrum: 0.2158516
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
